source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'WakupDemo' do

    # Wakup SDK
    pod 'Wakup', :path => '../'
    
    # Simple and highly customizable tag list view (force UIAppearance proxy commit)
    pod 'TagListView', :git => 'https://github.com/xhacker/TagListView.git', :commit => '44cc003fe2e701bdd603e7c9f64f7111439e2082'

end

# Workaround until https://github.com/CocoaPods/CocoaPods/issues/5334 is fixed
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end