source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'WakupDemo' do

    # Wakup SDK
    pod 'Wakup', :path => '../'
    
    # An easy-to-plug-in Contextual Menu for iOS inspired by Pinterest (fix for modal controllers fork)
    pod 'iOSContextualMenu', :git => 'https://github.com/redent/iOSContextualMenu.git'

end

# Workaround until https://github.com/CocoaPods/CocoaPods/issues/5334 is fixed
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end
